### ISSUE TITLE
How to start model?

### ISSUE THREAD

**Issue by PrimeTimeTran** [SilasMarvin/lsp-ai#13]
I've installed LSP-AI on my local

```sh
$ which lsp-ai

/Users/future/.cargo/bin/lsp-ai
```

But I don't know how to start it.
when I run 
```sh
$ /Users/future/.cargo/bin/lsp-ai             
```

The console hangs. If I press a key it exits immediately. 
Not sure what to do next. Please advise.

Thanks for your work!

**Comment by SilasMarvin** [comment]
Thanks for checking the project out. 

You should never have to start `lsp-ai` yourself. You should configure your text editor to do it for you. If you are using VS Code, we have an official VS Code plugin. If you are using helix or neovim, we have some example configurations available for those editors. If you are using a different editor, you will have to checkout your editors documentation around adding a new language server.

**Comment by PrimeTimeTran** [comment]
Thank for getting back so quickly!

I've already installed the plugin and tried both llama & open ai but neither worked. I wrote a comment, then moved my cursor down and invoked the LSP-AI generate but nothing happens.

**Comment by SilasMarvin** [comment]
Of course. What editor are you using? Can you share your config?

**Comment by PrimeTimeTran** [comment]
![todo](https://github.com/SilasMarvin/lsp-ai/assets/16382165/5c921714-3b7d-45fa-ab47-bdc1e8f84964)


<img width="2056" alt="Screenshot 2024-06-09 at 6 05 37 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/497e7d12-2aef-4ffb-89d7-fb476ee86b13">


```json
"lsp-ai.serverConfiguration": {
    "memory": {
      "file_store": {}
    },
    "models": {
      "model1": {
        "type": "llama_cpp",
        "repository": "stabilityai/stable-code-3b",
        "name": "stable-code-3b-Q5_K_M.gguf",
        "n_ctx": 2048
      }
    }
  },
  "lsp-ai.generationConfiguration": {
    "model": "model1",
    "parameters": {
      "fim": {
        "start": "<fim_prefix>",
        "middle": "<fim_suffix>",
        "end": "<fim_middle>"
      },
      "max_context": 2000,
      "max_new_tokens": 32
    }
  },
  "lsp-ai.inlineCompletionConfiguration": {
    "maxCompletionsPerSecond": 1
  },
```

Hope this helps. I think it's working cause I see a line added but there's no other indicator.

**Comment by SilasMarvin** [comment]
Thank you! In your VS Code terminal in the Output tab, can you change the dropdown from Window to `lsp-ai` and send me what it prints out? 

Are you on mac, did you install with `llama_cpp` and `metal` support?

**Comment by PrimeTimeTran** [comment]
Yes I did install with metal per suggestions in the README. Sorry I was trying to illustrate shortcut press. Here's the terminal output.

```sh
llama_kv_cache_init:      Metal KV buffer size =   640.00 MiB
llama_new_context_with_model: KV self size  =  640.00 MiB, K (f16):  320.00 MiB, V (f16):  320.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.19 MiB
llama_new_context_with_model:      Metal compute buffer size =   152.00 MiB
llama_new_context_with_model:        CPU compute buffer size =     9.01 MiB
llama_new_context_with_model: graph nodes  = 1095
llama_new_context_with_model: graph splits = 2
llama_new_context_with_model: n_ctx      = 2048
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      Metal KV buffer size =   640.00 MiB
llama_new_context_with_model: KV self size  =  640.00 MiB, K (f16):  320.00 MiB, V (f16):  320.00 MiB
llama_new_context_with_model:        CPU  output buffer size =     0.19 MiB
llama_new_context_with_model:      Metal compute buffer size =   152.00 MiB
llama_new_context_with_model:        CPU compute buffer size =     9.01 MiB
llama_new_context_with_model: graph nodes  = 1095
llama_new_context_with_model: graph splits = 2
```

**Comment by SilasMarvin** [comment]
Got it, that looks like its working then. I think it might be a setting in your VS Code configuration. 

Can you make sure your `Editor > Inline Suggest: Enabled` is checked. 

Also make sure the value of `Editor > Quick Suggestions` `other` is set to inline.

**Comment by PrimeTimeTran** [comment]
I've been wanting to find a os project to work on for some time now but hadn't had any luck. Felt like all other apps have been handled. I hope to be able to contribute to this one since it's so early and I'm sure you could use help and have other ideas. I haven't spun up an electron app is years though, lol. Also I know little about ML and even less about Rust so yeah... appreciate your work, looking forward to this becoming a "have to have" app on VSCode.

**Comment by SilasMarvin** [comment]
> I've been wanting to find a os project to work on for some time now but hadn't had any luck. Felt like all other apps have been handled. I hope to be able to contribute to this one since it's so early and I'm sure you could use help and have other ideas. I haven't spun up an electron app is years though, lol. Also I know little about ML and even less about Rust so yeah... appreciate your work, looking forward to this becoming a "have to have" app on VSCode.

I am absolutely looking for help. I have a bunch of ideas and would love to talk about what areas of development interest you! There is a ton of really exciting things to do here. 

A couple things to. If you are interested in the VS Code side of things, there is a lot still to do with the plugin we have written: https://github.com/SilasMarvin/lsp-ai/blob/main/editors/vscode/src/index.ts Copilot's plugin has a lot more built out features and while I don't necessarily think we need to match its features, I think there should be some discussion around what features we do want.

**Comment by PrimeTimeTran** [comment]
I just tried RSing VScode and I see this now.
ERROR lsp_ai::transformer_worker: generating response: environment variable not found
<img width="2056" alt="Screenshot 2024-06-09 at 6 20 47 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/d3f107ba-c254-4bac-adbc-45d3700c302f">

**Comment by SilasMarvin** [comment]
Can you close VS Code, go to your terminal in a directory you want to open with VS Code. Run `export LSP_AI_LOG=DEBUG` and then `code .`. 

This will Open VS Code with the environment variable `LSP_AI_LOG=DEBUG` which enables debugging for LSP-AI.

**Comment by PrimeTimeTran** [comment]
Regardless I have the OPEN AI one set actually. 
<img width="2056" alt="Screenshot 2024-06-09 at 6 22 18 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/e7f80335-0218-44c2-ba14-a5636ea6823d">

**Comment by SilasMarvin** [comment]
It looks like you meant to set the `auth_token` not the `auth_token_env_var_name` https://github.com/SilasMarvin/lsp-ai/wiki/Configuration#openai-compatible-apis

**Comment by PrimeTimeTran** [comment]
> > 
> If you are interested in the VS Code side of things, there is a lot still to do with the plugin we have written: https://github.com/SilasMarvin/lsp-ai/blob/main/editors/vscode/src/index.ts Copilot's plugin has a lot more built out features and while I don't necessarily think we need to match its features, I think there should be some discussion around what features we do want.
> 
> If you want to get more into the Rust / language server side of things, there is also a bunch to do there. I want to explore agent based systems and have some discussion around what integrating something like that directly into the backend would look like. I'm currently working on directory crawling and RAG.

Very interested in getting making something for progeny.  Lemme know what your ideas are and I'll have a look at it? It's your baby so I feel you should have that kinda executive product power right now.

**Comment by PrimeTimeTran** [comment]
> auth_token
That was it. Thanks~!

**Comment by SilasMarvin** [comment]
Glad I could help! Just a note, the responses from OpenAI right now are not going to be very good with the filler messages. You will want to replace those. I have a section on the wiki for prompting that may be worth looking at

**Comment by SilasMarvin** [comment]
> > > 
> > 
> > 
> > If you are interested in the VS Code side of things, there is a lot still to do with the plugin we have written: https://github.com/SilasMarvin/lsp-ai/blob/main/editors/vscode/src/index.ts Copilot's plugin has a lot more built out features and while I don't necessarily think we need to match its features, I think there should be some discussion around what features we do want.
> > If you want to get more into the Rust / language server side of things, there is also a bunch to do there. I want to explore agent based systems and have some discussion around what integrating something like that directly into the backend would look like. I'm currently working on directory crawling and RAG.
> 
> Very interested in getting making something for progeny. Lemme know what your ideas are and I'll have a look at it? It's your baby so I feel you should have that kinda executive product power right now.

I appreciate your thoughts. If you want to participate, I want you to build out something you are excited about too! Check out the following capabilities of Copilot: https://code.visualstudio.com/docs/copilot/overview Let me know what you think about these capabilities and if we should try and match them.

I'm going to mark this as closed but we can continue talking here, or you can create another issue for discussing a good feature to add.

**Comment by PrimeTimeTran** [comment]
<img width="2056" alt="Screenshot 2024-06-09 at 9 53 07 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/dabaadde-f0c3-4083-be1c-2e8d2b5b9090">
<img width="2056" alt="Screenshot 2024-06-09 at 9 53 09 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/2b94df4f-3507-4fea-88f8-b4fa7ea668c0">

I really am interested. I even tried to figure out how to fork the wiki and update it earlier but went in circles and gave up. lol.

I've noticed the results are what I expected, far from perfect. For example here the code blocks aren't complete. 

I also noticed when languages are "changed" the extension doesn't "catch up" quickly enough. For example imagine I'm building an app in Flutter/Dart but I have Python scripts to do certain things. If I switch from Python to Dart it still generates Python despite being in a `.dart` file.

Anyway not trying to nitpick just saying. In any case I ended up poking around and saw the extension isn't even using Electron as I initially thought but some other packages so I need to spend some time getting familiar with those. Concerning CoPilot extension, undoubtedly, I'd love to be able to add those so gimme some time to do some research on these libs.

**Comment by SilasMarvin** [comment]
What prompt are you using? The prompt will have a massive impact on how well the LLM performs. 

The Python and Dart mixup is interesting. We don't actually specify the language the LLM is supposed to complete, we just pass it the code / comments around the cursor (this also depends on which prompt system you are using), so if you have Python or Dart code around the cursor it should complete correctly, but not always as LLMs are not deterministic and do have some strange quirks. 

That sounds great! Let me know what you think, and feel free to make a pull request anytime!

**Comment by PrimeTimeTran** [comment]
Isn't it on line 85, the comment? 

We prompt the AI in comments is my understanding . However it's been a while since I used one so correct me if I'm wrong.

**Comment by SilasMarvin** [comment]
Take a look at the prompting guide on the wiki: https://github.com/SilasMarvin/lsp-ai/wiki/Prompting

There is a lot more that goes into it.

**Comment by PrimeTimeTran** [comment]
> and feel free to make a pull request anytime!

I'm looking forward to it. I think a killer feature which is missing in these types of tools(in my limited experimentation) is that we should be able to tag/label the file and that's combined with the inline comment/prompt. In this way I would expect the model to prodcuce better results. Like add a comment on line 1 and that's always sent with the subsequent prompt requests.

**Comment by SilasMarvin** [comment]
That is a really cool idea! We could add some kind of keyword like:`LSP-AI Tag` and then search for it in the current file, and make it a . 

A user working on a Python file could use it like so:
```
# LSP-AI Tag: This file is implementing a fibonnaci sequence 

def fib
```

Then it could become a variable they can use when building the prompt. 

E.G.

```
{
  "messages": [
    {
      "role":"system",
      "content":"You are a programming completion tool. Replace <CURSOR> with the correct code."
    },
    {
      "role": "user",
      "content": "{LSP-AI_TAG}\n{CODE}"
    }
  ]
}
```

**Comment by PrimeTimeTran** [comment]
Sure I think the implementation could work like that. My main idea though is that by labeling a bunch of files, collectively they can be joined to deliver much more specific/fine tuned results. 

Imagine the README labels the repo as a CSM app which the AI recognizes.  It also defines framework/dependencies for the project. The AI could then, like you said earlier, use RAG to build more context for the next methods/modules/resources it generates inside in nested files/directories.

I would hope provided that a dev could then create a new file named `User.model.js`  and then the model would be able to, without prompt, generate a basic dependency definition for a user model(sequelize vs moongoose for example).

**Comment by SilasMarvin** [comment]
This is a really interesting idea. Let me think on this some more and get back to you on it. I did just implement crawling of the code base in: https://github.com/SilasMarvin/lsp-ai/pull/14 Which will give us some good groundwork to build off of.

There definitely needs to be some thought put into how we build that kind of context for the model. Ideally it wouldn't have to be something the user does manually. It could be part of an agent system where we have an LLM who's job it is to tag files and build the context for the LLM to do completion?

I'll think more on this. Really good suggestions thank you, I'm excited to work on this together!

**Comment by PrimeTimeTran** [comment]
<img width="2056" alt="Screenshot 2024-06-09 at 10 55 59 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/a89ffc3f-d252-4532-b354-d31f86299273">

I read the prompts docs you provided but still don't quite get it. Those looked like generation data to me, multiply & is_event for example. 

The prompts should be similar to what I've done on line 16 I thought? Tell the AI what I want, fix the error, and it picks up the context by itself. 

<img width="2056" alt="Screenshot 2024-06-09 at 11 06 30 PM" src="https://github.com/SilasMarvin/lsp-ai/assets/16382165/8abad163-dd84-4b94-a937-e0c2987de581">

Here's another example of what I **think** the expected behavior should be, that the AI can pickup comments and generate from there. Hopefully it would be able to not do what it's doing right here and suggestions the exact same thing again...?

Yeah me too. Gimme some time, to catch up on what you've already done and I'll try to figure out how to "switch" the prompt/context. Unsure of what else the explanation is for this time of generation is currently...

**Comment by SilasMarvin** [comment]
The prompts that I have written for OpenAI are designed to make it perform code completion. You can alter the prompts however you see best! If you want to tell it what you want, and have it generate the code that way, you totally can. Just later the messages you send

**Comment by PrimeTimeTran** [comment]
Here's my generation prompt config. 

```sh
"lsp-ai.generationConfiguration": {
    "model": "model1",
    "parameters": {
      "max_tokens": 2000,
      "max_context": 3000,
      "messages": [
        {
          "role": "system",
          "content": "You are a Generative AI fine tuned for software development. You've mastered mobile, web, and AI/ML concepts, languages, frameworks, & conventions. You help the user complete the code you're provided."
        },
        {
          "role": "user",
          "content": "{CODE}"
        }
      ]
    }
  },
```

Take away for me is that despite defining a much higher token allocation it failed to provide the "complete" code. Not sure what the issue if, my prompt in the config or the editor...? 

Slow and steady, lol =)

**Comment by SilasMarvin** [comment]
That is strange it is not providing the complete code. I would test in their playground and see if it works there? Maybe they have some hidden API limits? I don't think our request is malformed. 

Slow and steady wins the race!
