### ISSUE TITLE
Support remote endpoint for Ollama?

### ISSUE THREAD

**Issue by luixiao0** [SilasMarvin/lsp-ai#16]
Thanks for this project

### Is there an existing issue for this?
   I have searched the existing issues

### Feature request
   Support remote endpoint for Ollama

### Context
   ollama is not fast enough using onboard hardware if run on laptops locally, we can utilize exising cloud GPUs to speed it up

Possible implementation
  I have provided a possible implementation at https://github.com/SilasMarvin/lsp-ai/pull/15

**Comment by SilasMarvin** [comment]
This is great! I added it yesterday and honestly didn't even think about a remote api. I added a few comments in the PR, but otherwise it looks really awesome!

**Comment by luixiao0** [comment]
resolved by #15
