### ISSUE TITLE
Update cargo lockfile for frozen builds

### ISSUE THREAD

**Issue by AgentElement** [SilasMarvin/lsp-ai#20]
Running `cargo build --frozen` fails for release 0.2.0. I am trying to package 0.2.0 for nixos, but the lockfile being behind makes it so that I cannot do so. An easy fix is to update the lockfile and bump the version to (say) 0.2.1.

Steps to reproduce:

Run `cargo build --frozen`

Output:
```
error: the lock file /path/to/lsp-ai/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

**Comment by SilasMarvin** [comment]
Thanks for pointing this out! I just updated the Cargo.lock here: https://github.com/SilasMarvin/lsp-ai/pull/22

Would love to have a flake for this if that is something you would want to add!

**Comment by AgentElement** [comment]
Sure, I can make a PR when I have a flake ready.
