### ISSUE TITLE
VS code 

### ISSUE THREAD

**Issue by Eyobs-droid** [SilasMarvin/lsp-ai#21]
[Error - 5:16:50 PM] lsp-ai client: couldn't create connection to server.
Launching server using command lsp-ai failed. Error: spawn lsp-ai ENOENT

The following error shows on vs code insiders

**Comment by luixiao0** [comment]
you might want to run cargo install to install lsp-ai executable to PATH

**Comment by SilasMarvin** [comment]
Make sure to install the server before enabling the VS Code plugin: https://github.com/SilasMarvin/lsp-ai/wiki/Installation
