### ISSUE TITLE
Add google generative language api support

### ISSUE THREAD

**Issue by asukaminato0721** [SilasMarvin/lsp-ai#28]
https://aistudio.google.com/app/prompts/new_chat

currently it's free.

usage

```sh
curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}' \
  -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=YOUR_API_KEY'
```

**Comment by SilasMarvin** [comment]
We do not currently but this sounds like a great option to support! Adding this into the roadmap. I will post some updates here. You are also welcome to add it if you want, it's not too difficult to add a backend if you have some experience with Rust. I'm happy to point you in the right direction.
