### ISSUE TITLE
bug: lsp_ai::transformer_worker: generating response: specify `completions_endpoint` to use completions. Wanted to use `chat` instead?

### ISSUE THREAD

**Issue by 4t8dd** [SilasMarvin/lsp-ai#40]
My Os is MacOS, M2. 

The config of vscode is:
```
{
  "lsp-ai.serverConfiguration": {
    "memory": {
      "file_store": {}
    },
    "models": {
      "model1": {
        "type": "open_ai",
        "chat_endpoint": "https://api.openai.com/v1/chat/completions",
        "model": "gpt-4o",
        "auth_token": "sk-codefB2"
      }
    }
  },
  "lsp-ai.generationConfiguration": {
    "model": "model1",
    "parameters": {
      "max_tokens": 128,
      "max_context": 1024,
      "messages": [
        {
          "role": "system",
          "content": "You are a programming completion tool. Replace <CURSOR> with the correct code."
        },
        {
          "role": "user",
          "content": "{CODE}"
        }
      ]
    }
  },
  "lsp-ai.inlineCompletionConfiguration": {
    "maxCompletionsPerSecond": 1
  }
}


```
The error I got is:

ERROR lsp_ai::memory_worker: error in memory worker task: Error file not found
ERROR dispatch_request{request=Generation(GenerationRequest { id: RequestId(I32(124)), params: GenerationParams { text_document_position: TextDocumentPositionParams { text_document: TextDocumentIdentifier { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/Users/mme/repos/fib.py", query: None, fragment: None } }, position: Position { line: 1, character: 14 } }, model: "model1", parameters: Object {"max_context": Number(2048), "max_tokens": Number(128)}, post_process: PostProcess { remove_duplicate_start: true, remove_duplicate_end: true } } })}: lsp_ai::transformer_worker: generating response: specify `completions_endpoint` to use completions. Wanted to use `chat` instead? Please specify `chat_endpoint` and `messages`.
DEBUG lsp_server::msg: > {"jsonrpc":"2.0","id":124,"error":{"code":-32603,"message":"specify `completions_endpoint` to use completions. Wanted to use `chat` instead? Please specify `chat_endpoint` and `messages`."}}
```

Some issue in my config? Or I missed anything. Please help me out before I have to read the rust code.

**Comment by SilasMarvin** [comment]
You config looks ok. I'm not sure why you are getting that error. Does it happen every time? Is it random?

 Its also worth double checking that you didn't post a real key here? If that is your auth token please remove it or someone may use it.

I was able to verify that the VS Code extension works with the latest version of LSP-AI. My entire VS Code config:
```
{
  "workbench.colorTheme": "Gruvbox Dark Hard",
  "vim.cursorStylePerMode.normal": "block",
  "editor.quickSuggestions": {
    "other": "inline"
  },
  "extensions.ignoreRecommendations": true,
  "editor.quickSuggestionsDelay": 50,
  "lsp-ai.serverConfiguration": {
    "memory": {
      "file_store": {}
    },
    "models": {
      "model1": {
        "type": "open_ai",
        "chat_endpoint": "https://api.openai.com/v1/chat/completions",
        "model": "gpt-4o",
        "auth_token_env_var_name": "OPENAI_API_KEY"
      }
    }
  },
  "lsp-ai.generationConfiguration": {
    "model": "model1",
    "parameters": {
      "max_tokens": 128,
      "max_context": 1024,
      "messages": [
        {
          "role": "system",
          "content": "You are a programming completion tool. Replace <CURSOR> with the correct code."
        },
        {
          "role": "user",
          "content": "{CODE}"
        }
      ]
    }
  },
  "lsp-ai.inlineCompletionConfiguration": {
    "maxCompletionsPerSecond": 1
  } 
}
```

**Comment by 4t8dd** [comment]
yeah, I found the cause. I have another extension which got the same functionality as lsp-ai. When I disabled it, it returned.
So I close this issue. 

But I got some insteresting and I would like to share. I opened a rust project then I create a python file in the same vscode.
When I play the example code, I would expect fib function. But I got some unexpected rust code part of which definitely is from the rust project. BTW, the rust project is lsp-ai. You can find the result as the screenshot below:

![Screenshot 2024-07-20 at 6 22 53 PM](https://github.com/user-attachments/assets/f3ffaa69-1b2b-4a0c-a0cb-bd44d265f100)

and this one:
![Screenshot 2024-07-20 at 6 38 29 PM](https://github.com/user-attachments/assets/87cc7d74-ac90-4dbe-9d6d-427f7d0e43b2)

The file is a python file.
But when I just tell explicitly in the comment using python. Then the result is fine. 

![Screenshot 2024-07-20 at 6 40 49 PM](https://github.com/user-attachments/assets/c799c24b-1a79-4543-9068-a9495b213618)

Nice.

**Comment by 4t8dd** [comment]
The api key is fake though. Thanks for the remind.
