### ISSUE TITLE
User help with Helix

### ISSUE THREAD

**Issue by noahfraiture** [SilasMarvin/lsp-ai#43]
Hello, 
I'm trying to get things work but it doesn't and I don't know why. I used the configuration here [https://github.com/SilasMarvin/lsp-ai/blob/main/examples/helix/openai-chat.toml](url) in rust and I simply changed 
```
chat_endpoint = "https://api.groq.com/openai/v1/chat/completions"
auth_token_env_var_name = "GROQ_API_KEY"
```

I'm mostly here to ask if there's any logs to debug that

**Comment by SilasMarvin** [comment]
There is a section on the wiki for debugging but basically just set the env variable `LSP_AI_LOG` to `DEBUG`:
```bash
export LSP_AI_LOG=DEBUG
```

Logs for helix typically go in the `~/.cache/helix/helix.log` file. You should see error messages there.

**Comment by noahfraiture** [comment]
Great thank you ! The logs seem to flag every thing as error even they aren't but I was able to fix the issue
