### ISSUE TITLE
An error occurred with the VSCode extension.

### ISSUE THREAD

**Issue by kiyo-e** [SilasMarvin/lsp-ai#62]
An error occurred with the VSCode extension.
Upon checking the logs, it says:
`error: unexpected argument '--stdio' found`

Here is the full error message:
```
error: unexpected argument '--stdio' found

Usage: lsp-ai [OPTIONS]

For more information, try '--help'.
[Error - 0:27:23] Server process exited with code 2.
[Error - 0:27:23] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 0:27:23] Connection to server got closed. Server will restart.
true
[Error - 0:27:23] lsp-ai client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

versions:
lsp-ai 0.6.0
VSCode extension: 0.1.0

**Comment by SilasMarvin** [comment]
Thanks for bringing this up! I recently added some command line arguments to LSP-AI for file logging and apparently vscode was always passing the `--stdio` argument which isn't a real argument we accept as we always communicate over stdio. I added `--stdio` as an argument though it doesn't actually do anything for now. 

Patched in: https://github.com/SilasMarvin/lsp-ai/releases/tag/v0.6.1
