### ISSUE TITLE
Add binary to Github Release

### ISSUE THREAD

**Issue by kharf** [SilasMarvin/lsp-ai#65]
Many don't want to use multiple package managers (cargo in this case) for maintaining packages.
Adding the precompiled binary to Github releases would make it easier to publish it to most common package managers.

**Comment by SilasMarvin** [comment]
This is a good point. I will make sure to use the release action going forward. https://github.com/SilasMarvin/lsp-ai/releases/tag/v0.6.2

**Comment by kharf** [comment]
> This is a good point. I will make sure to use the release action going forward. https://github.com/SilasMarvin/lsp-ai/releases/tag/v0.6.2

Thank you!
