### ISSUE TITLE
running the LSP on a remote machine / using a remote LLM LSP server: documentation / if necessary general implementation (?)

### ISSUE THREAD

**Issue by jerabaul29** [SilasMarvin/lsp-ai#67]
Many thanks again for an awesome tool :) .

If I understand correctly, it is possible to run the LSP on a remote machine (for example running the LSP on a GPU server, while coding on a laptop, at least for a specific LLM backend https://github.com/SilasMarvin/lsp-ai/pull/15 ).

This is actually a common user case I think - for example at companies, it would be much more convenient to have a shared GPU server running the LLMs, and employees connecting their LSP editor client to it, rather than each employee getting a GPU and running a LLM server on their own machine.

It is not clear to me if the use of a remote server to actually run the LLM is only supported for a specific model after the PR above, or if it is a general feature. If it was possible to support it as a general feature, this would be very convenient :) . Not sure what the architecture of lsp-ai is at now, and not sure for example if the server vs "client" part of the LSP are decoupled and if this would be as simple as ssh-piping from a machine running the LLM to the local machine on a given port. Could this be documented / explained as an example of deployment? :)

This would have a lot to say for adoption, since I am afraid at present it is not realistic to hope that each developer would have a powerful enough GPU in their machine running a LLM, and without such hardware, the models that can be run are very small due to both latency and overall memory use considerations :) .

**Comment by SilasMarvin** [comment]
I'm glad you like it!

LSP-AI is a language server: https://en.wikipedia.org/wiki/Language_Server_Protocol It is designed to be run locally on your computer alongside the editor you are using. You should not host LSP-AI remotely. 

GPUs  become useful when doing text-generation with large LLMs. For this use case, LSP-AI supports making API requests. LSP-AI can make API requests to:
- OpenAI or OpenAI compatible APIs like fireworks, VLLM, etc...
- Anthropic or Anthropic compatible APIs
- Ollama

The API you use is dependent on the model you want to use. The endpoints are all configurable. See: https://github.com/SilasMarvin/lsp-ai/wiki/Configuration

Let me know if you have any other questions. I really do need to improve the general documentation around configurations and how to properly use it.
