### ISSUE TITLE
Add support for external config file

### ISSUE THREAD

**Issue by zaytsev** [SilasMarvin/lsp-ai#68]
It would be nice to have ability to configure lsp-ai with external file, instead of embedding config into helix `languages.toml`

Context:
I created module for [home-manager](https://github.com/nix-community/home-manager) to have a sort of type/syntax checked config generator and only then found out that there is no direct way to feed generated JSON into lsp-ai

**Comment by SilasMarvin** [comment]
I agree this would be nice and really simple to add. Feel free to add it if you want. You would want to edit the main.rs file to take a path name as a command line argument, read it in, and pass it to the Config. Note that if they also pass `initializationOptions` I would say those should override the file if they aren't empty.

If you don't want to add it I can probably get to it in the next few weeks. I'm working on an online configurator for LSP-AI that is taking most of my free time.
