### ISSUE TITLE
How to use it in Kate editor?

### ISSUE THREAD

**Issue by Leroy-X** [SilasMarvin/lsp-ai#72]
Hi, I am a newbie and unfamiliar with this. 
Does lsp-ai support Kate editor?  and how to use it in Kate?

Thanks.

**Comment by SilasMarvin** [comment]
I'm not very familiar with the Kate editor. If the Kate editor supports the language sever protocol it will work in Kate. You will need to look at the Kate docs for setting up a custom language server and add LSP-AI. You will need to find out how to pass initializationOptions and pass the config you want. An example of that is outside the scope of an issue with LSP-AI so I am going to close this, but feel free to make a pr to add an example with Kate.

**Comment by frainfreeze** [comment]
@Leroy-X did you ever manage to get this to work?

**Comment by Leroy-X** [comment]
@frainfreeze During my last test after the update, the menu was visible, but clicking on it didn’t trigger any response. I haven’t followed up with further testing since then.

**Comment by frainfreeze** [comment]
That's exactly where I got stuck too. Will update if I get through. Tnx for quick reply!
