### ISSUE TITLE
[Question] Is it possible to use Ollama as a backend?

### ISSUE THREAD

**Issue by curldivergence** [SilasMarvin/lsp-ai#9]
Hi, first of all - thank you for an awesome project :)
I have a question though - the docs say that when `llama.cpp` backend is used, the LSP links directly to it, but I'm not sure - is it possible to utilize an Ollama instance serving on the local network?
Thanks!

**Comment by SilasMarvin** [comment]
This sounds like it would be a great addition. I will add Ollama support today. Stay tuned!

**Comment by SilasMarvin** [comment]
Added Ollama here! https://github.com/SilasMarvin/lsp-ai/pull/11 Pushing out a new release now
